### PR TITLE
Added a missing quote in etcd.manifest

### PR DESCRIPTION
**Pull request by jshaofuturewei**
It does not matter. However, it is better to fix it.

### CODE REVIEW

**Review by Sindica — APPROVED** [review]

**Comment by pdgetrf** [comment]
what's the impact of this misspell before this fix?

**Comment by jshaofuturewei** [comment]
> what's the impact of this misspell before this fix?

It is used by migrate-if-needed.sh for an etcd version that can be migrated to. migrate-if-needed.sh is not triggered in arktos since we don't have any version that we need to migrate to.

**Comment by pdgetrf** [comment]
> > what's the impact of this misspell before this fix?
> 
> It is used by migrate-if-needed.sh for an etcd version that can be migrated to. migrate-if-needed.sh is not triggered in arktos since we don't have any version that we need to migrate to.

how did this pass the test done for the previous PR that merged it in?

**Comment by jshaofuturewei** [comment]
> > > what's the impact of this misspell before this fix?
> > 
> > 
> > It is used by migrate-if-needed.sh for an etcd version that can be migrated to. migrate-if-needed.sh is not triggered in arktos since we don't have any version that we need to migrate to.
> 
> how did this pass the test done for the previous PR that merged it in?

There is no migration scenario or test case to use the variable for arktos.

**Comment by pdgetrf** [comment]
> > > > what's the impact of this misspell before this fix?
> > > 
> > > 
> > > It is used by migrate-if-needed.sh for an etcd version that can be migrated to. migrate-if-needed.sh is not triggered in arktos since we don't have any version that we need to migrate to.
> > 
> > 
> > how did this pass the test done for the previous PR that merged it in?
> 
> There is no migration scenario or test case to use the variable for arktos.

was it manually tested on a local environment at least?

**Comment by jshaofuturewei** [comment]
> > > > > what's the impact of this misspell before this fix?
> > > > 
> > > > 
> > > > It is used by migrate-if-needed.sh for an etcd version that can be migrated to. migrate-if-needed.sh is not triggered in arktos since we don't have any version that we need to migrate to.
> > > 
> > > 
> > > how did this pass the test done for the previous PR that merged it in?
> > 
> > 
> > There is no migration scenario or test case to use the variable for arktos.
> 
> was it manually tested on a local environment at least?

In an etcd container, run export and you will see the TARGET_VERSION


declare -x TARGET_STORAGE="etcd3"
declare -x TARGET_VERSION="3.4.3"
declare -x TERM="xterm"

**Pull request merged**
