### PR TITLE
Universal etcd key

### PR DESCRIPTION
**Pull request by chenqianfzh**
## What is this PR about?
This PR address issue https://github.com/futurewei-cloud/arktos/issues/339.

With this change, the resources under the system tenant and the regular tenants will have the same format etcd key format, namely, /registry/{resources}/{tenant}/{namespace}/{name}.

## Split Commits For Easy Reviewing

As about 300 files are involved in this change, I split the code change into 3 commits, for the convenience of code reviewers:
1. commit "consistent etcd keys path for all tenants". This is the critical part of this changes. It does:
 a. change the etcd key path.
 b. update informer/lister per the change in etcd key path. As the system-tenant resources and all-tenant resources have the same etcd key prefix ( both have the tenant field skipped) before this change, the existing watch-all-tenant informers have the tenant field set to "system" as it means minimal code change to watch/list/get operations. With this etcd key path change, I have to update the tenant in these informers from "system" to "all".

2. commit "update tests"

3. commit "auto updates": it is the auto-updated code due to the change in informer/lister template.

## Verification Done in my Dev Box

After cluster is up with Arktos-up.sh, run the following command to get the etcd keys. Here are the excerpt of the output ( the whole output is very long). You can see the the tenant of "system" appear in the etcd key.

```

ETCDCTL_API=3 etcdctl get "" --prefix=true --keys-only

...
/registry/serviceaccounts/system/kube-system/tenant-controller

/registry/serviceaccounts/system/kube-system/ttl-controller

/registry/serviceaccounts/system/kube-system/virtlet

/registry/serviceaccounts/system/kube-system/vm-pod-controller

/registry/services/endpoints/system/default/kubernetes

/registry/services/endpoints/system/kube-system/kube-dns

/registry/services/specs/system/default/kubernetes

/registry/services/specs/system/kube-system/kube-dns
...
```

### CODE REVIEW

**Comment by Sindica** [comment]
Tested in multiple api server partitioned environment. (https://github.com/futurewei-cloud/arktos/blob/master/docs/setup-guide/arktos-apiserver-partition.md)

1. Start arktos-up.sh on server 1, start "arktos-apiserver-partition.sh start_apiserver <ETCD server ip>" on server 2.
2. Apply data partition yml for server 1 and 2.
3. Create tenant aa, create namespace a.
4. Create deployment for tenant aa.
Expecting result:
deployment.apps/nginx-deployment created

Actual result:
Error from server (NotFound): error when creating "/home/yinghuang/K8s-spec/deployment-tenant-a.yml": tenants "aa" not found

**Comment by Sindica** [comment]
> Tested in multiple api server partitioned environment. (https://github.com/futurewei-cloud/arktos/blob/master/docs/setup-guide/arktos-apiserver-partition.md)
> 
> 1. Start arktos-up.sh on server 1, start "arktos-apiserver-partition.sh start_apiserver " on server 2.
> 2. Apply data partition yml for server 1 and 2.
> 3. Create tenant aa, create namespace a.
> 4. Create deployment for tenant aa.
>    Expecting result:
>    deployment.apps/nginx-deployment created
> 
> Actual result:
> Error from server (NotFound): error when creating "/home/yinghuang/K8s-spec/deployment-tenant-a.yml": tenants "aa" not found

Worked with Qian. tenants not found seems an known transient issue. The real problem with this code change is kubelet seems not getting informed and not able to schedule pod correctly.

**Comment by chenqianfzh** [comment]
> > Tested in multiple api server partitioned environment. (https://github.com/futurewei-cloud/arktos/blob/master/docs/setup-guide/arktos-apiserver-partition.md)
> > 
> > 1. Start arktos-up.sh on server 1, start "arktos-apiserver-partition.sh start_apiserver " on server 2.
> > 2. Apply data partition yml for server 1 and 2.
> > 3. Create tenant aa, create namespace a.
> > 4. Create deployment for tenant aa.
> >    Expecting result:
> >    deployment.apps/nginx-deployment created
> > 
> > Actual result:
> > Error from server (NotFound): error when creating "/home/yinghuang/K8s-spec/deployment-tenant-a.yml": tenants "aa" not found
> 
> Worked with Qian. tenants not found seems an known transient issue. The real problem with this code change is kubelet seems not getting informed and not able to schedule pod correctly.

Updated. Please try again.

**Comment by Sindica** [comment]
. Can you change the storageClusterId from "system" to "0"?
. Create a deployment in any tenant (even for default system tenant), pod status will not be ready.

**Comment by chenqianfzh** [comment]
> > > Tested in multiple api server partitioned environment. (https://github.com/futurewei-cloud/arktos/blob/master/docs/setup-guide/arktos-apiserver-partition.md)
> > > 
> > > 1. Start arktos-up.sh on server 1, start "arktos-apiserver-partition.sh start_apiserver " on server 2.
> > > 2. Apply data partition yml for server 1 and 2.
> > > 3. Create tenant aa, create namespace a.
> > > 4. Create deployment for tenant aa.
> > >    Expecting result:
> > >    deployment.apps/nginx-deployment created
> > > 
> > > Actual result:
> > > Error from server (NotFound): error when creating "/home/yinghuang/K8s-spec/deployment-tenant-a.yml": tenants "aa" not found
> > 
> > 
> > Worked with Qian. tenants not found seems an known transient issue. The real problem with this code change is kubelet seems not getting informed and not able to schedule pod correctly.
> 
> Updated. Please try again.

Fixed. Please try again.

**Comment by Sindica** [comment]
I recently made changes to the format of StorageClusterId for tenant. It needs to be string type integer now. Please use "0" for system cluster id.

**Comment by chenqianfzh** [comment]
> I recently made changes to the format of StorageClusterId for tenant. It needs to be string type integer now. Please use "0" for system cluster id. The code change was merged yesterday.

The StorageClusterId change breaks the command of "kubectl create tenant". I sent out a fixing PR at https://github.com/futurewei-cloud/arktos/pull/464 and you are the reviewer.

Besides, I did not see the StorageClusterId change relates to this PR of etcd key path. Does it?

**Comment by Sindica** [comment]
> > I recently made changes to the format of StorageClusterId for tenant. It needs to be string type integer now. Please use "0" for system cluster id. The code change was merged yesterday.
> 
> The StorageClusterId change breaks the command of "kubectl create tenant". I sent out a fixing PR at #464 and you are the reviewer.
> 
> Besides, I did not see the StorageClusterId change relates to this PR of etcd key path. Does it?
What do you mean? It was merged in this squashed commit: https://github.com/futurewei-cloud/arktos/commit/ac1d0cf7da821f8b2c740e4dc3d6445526944f3c

The related commit: https://github.com/futurewei-cloud/arktos/pull/451/commits/29e1997ce250369642d2231ffb57fdc8497b737a

**Pull request closed without merging**
